services:
  localstack:
    container_name: localstack-main
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - DEBUG=1
      - LOCALSTACK-CLI=1
      - ACTIVE-PRO=0
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=s3,lambda,dynamodb,apigateway,iam,cloudwatch,cloudformation
      - AWS_SECRET_ACCESS_KEY=000000000000
      - AWS_ACCOUNT_ID=000000000000
    privileged: true
    # healthcheck:
    #   test: ["CMD", "awslocal lambda list-functions"]
    #   interval: 1m30s
    #   timeout: 30s
    #   retries: 5
    #   start_period: 30s

  web:
    container_name: chatbot-web
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_PORT-3000
    volumes:
      - ./web/node_modules:/app/node_modules
      - ./web:/app
    ports:
      - 3000:3000
