services:
  localstack:
    container_name: localstack-main
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - LS_LOG=trace
      - DEBUG=1
      - EAGER_SERVICE_LOADING=0
      - LOCALSTACK-CLI=1
      - ACTIVE_PRO=0

      - LAMBDA_DOCKER_FLAGS=-e TEST_LAMBDA_ENV_VAR=VALUE
      - SERVICES=s3,lambda,dynamodb,apigateway,iam,cloudwatch,cloudformation
      - SET_TERM_HANDLER=1
      - AWS_DEFAULT_REGION=eu-west-3
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test   
      - AWS_ACCOUNT_ID=000000000000
      - DOCKER_HOST=unix:///var/run/docker.sock
      - GATEWAY_LISTEN=0.0.0.0:4566
      - DATA_DIR=/tmp/localstack/data
      - HOSTNAME_FROM_LAMBDA=localstack-main
      - LOCALSTACK_HOST=localstack-main
      - MAIN_CONTAINER_NAME=localstack-main
      # - LAMBDA_REMOVE_CONTAINERS=0
      # - LAMBDA_RUNTIME_EXECUTOR=docker
      - SAM_CLI_TELEMETRY=0
    volumes:
      - /home/yuval/.cache/localstack/volume:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: bridge
    
    # healthcheck:
    #   test: ["CMD", "awslocal lambda list-functions"]
    #   interval: 1m30s
    #   timeout: 30s
    #   retries: 5
    #   start_period: 30s

  web:
    container_name: chatbot-web
    build:
      args:
        - REACT_APP_PORT=3000
        - REACT_APP_HOST=0.0.0.0
        - REACT_APP_HOST_ENDPOINT=http://localhost
        - REACT_APP_PORT_ENDPOINT=3001
      context: ./web
      dockerfile: Dockerfile.prod
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true    
    # volumes:  during development fast reloading
    #   - ./web/node_modules:/app/node_modules
    #   - ./web:/app
    ports:
      - 3000:3000
